[build-system]
requires = ["setuptools>=42.0","wheel"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
addopts = "--cov=src/dana --cov-report=term-missing -v -W ignore::DeprecationWarning --basetemp=src/test/tmp"
testpaths = ["src/test",]

[tool.isort]
profile = "black"